name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  flutter_svg: ^1.0.3
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  rubber: ^1.1.0
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
 #  fonts:
  #   - family: Schyler
   #    fonts:
    #     - asset: fonts/Schyler-Regular.ttf
     #    - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
